// Code generated by gala; DO NOT EDIT.
// This file simulates a transpiler output (.gen.go) on disk; the extension
// must NOT treat it as a hand-written Go source when detecting mixed packages.
package mixedgopkg

func Sizes(xs []int) int { return len(xs) }
